import choose_faculty as choose_fac

def modify(c1,conn):
    roll_no=int(input("Enter your roll number: "))
    mysql="select*from hostel_management where roll_no={}".format(roll_no)
    c1.execute(mysql)
    data=c1.fetchall()
    print("Roll_no:",data[0][0])
    print("Name:",data[0][1])
    print("Address:",data[0][2])           
    print("Room_no:",data[0][3])
    print("Dept:",data[0][4])
    print("Fees:",data[0][5])           
    print("Bal:",data[0][6])
    print("\nPlease update the data: \n")
    v_roll=input("ENTER YOUR ROLL NUMBER: ")
    v_name=input("ENTER YOUR NAME: ")
    v_add=input("ENTER YOUR ADDRESS: ")
    v_room_no=input("ENTER YOUR ROOM NUMBER: ")
    v_dept=choose_fac.choose_faculty()
    v_fees=input("ENTER YOUR FEES: ")
    v_bal=input("ENTER YOUR BALANCE: ")
    update_sql = ("UPDATE hostel_management SET roll_no = '%s',name ='%s',address ='%s', room_no = '%s', dept = '%s', fees = '%s',bal = '%s' where roll_no ='%d'"%(v_roll,v_name,v_add,v_room_no,v_dept,v_fees,v_bal,roll_no))
    c1.execute(update_sql)
    conn.commit()
    print("\nData updated successfully.")